### PR TITLE
Iss 311

### LINKED ISSUE #311: Bug: Results Stories/Transition Page are broken
The stories are broken for these components. 
DOD: 
Make code changes to remove these errors. 
image
image

### PR DESCRIPTION
**Pull request by jedpittman**
closes #311

### CODE REVIEW

File: frontend/src/ui/ErrorBoundary.tsx [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+interface errorBoundaryState {
+  hasError: boolean;
+}
+
+export const ThrowsError = () => {
+  throw exception('This is failing.');
+};
+
+export default class ErrorBoundary extends React.Component<
```
Comment (alexjball) [inline frontend/src/ui/ErrorBoundary.tsx:12]: I think this is part of another PR. Can we remove this?

File: frontend/src/ui/Results/Results.stories.tsx [hunk 2]
```diff
@@ -5,27 +5,44 @@ import occupations from '../../testing/data/occupations';
...
+import { createStore } from '../../ducks';
 
 export default {
   title: 'JobHopper/Results',
   component: Results,
 } as Meta;
 
-const Template: Story<ResultsProps> = args => <Results {...args} />;
+const Template: Story<ResultsProps> = args => (
+  <Provider store={createStore()}>
```
Comment (alexjball) [inline frontend/src/ui/Results/Results.stories.tsx:17]: Rather than provide the Results component with a redux store, I think we want to remove the redux usage from the Result component. Redux is anything from src/ducks. So it looks like we need to remove this line https://github.com/codeforboston/jobhopper/blob/d73ad6030c6a8fe8866c95fd3de5b1915e81ef9a/frontend/src/ui/Results/Results.tsx#L37 from the component. The component already has selectedState as a prop so I believe we can replace usages of state in there with selectedState

File: frontend/src/ui/Results/ResultsContainer.tsx [hunk 3]
```diff
@@ -12,13 +12,10 @@ import {
 import Results from './Results';
 
 export const ResultsContainer = () => {
-  const {
```
Comment (alexjball) [inline frontend/src/ui/Results/ResultsContainer.tsx:15]: I think we can revert changes to this file

**Review by alexjball — CHANGES_REQUESTED** [review]

File: frontend/src/ui/ErrorBoundary.tsx (hunk 1 above)
Comment (jedpittman) [reply frontend/src/ui/ErrorBoundary.tsx]: removed as part of updates.

File: frontend/src/ui/Results/Results.stories.tsx (hunk 2 above)
Comment (jedpittman) [reply frontend/src/ui/Results/Results.stories.tsx:16]: fixed.

**Comment by LewisStaples** [comment]
I confirm that the errors described in the issue are corrected.
All changes in the files appear directly related to the issue description.
I confirm that all tests run successfully on my machine.



Please note that Github has identified two warnings in 
frontend/src/ui/Results/Results.stories.tsx

(1) 'Provider' is defined but never used
(2) 'createStore' is defined but never used

I see that both are imported.  The code that uses them has been commented out,
therefore I suggest removing the two import statements, and all code that uses them.
(I saw no issues when I did that and tested it on my local machine)

**Comment by jedpittman** [comment]
Thanks for the review @LewisStaples ; merging this code in now.
