### PR TITLE
[ISS-366] Fixes for wording

### LINKED ISSUE #366: Miscellaneous Text Changes
Miscellaneous Text Changes:

We want to make sure it's totally clear to people what this website does. What do you think about the title saying "Which occupations do people switch to?" rather than "Occupation transitions"

I want to make it clear that the state-level aspect is just for the wages and the transition-level aspect is national. What do you think about the following for the text underneath "Enter Occupation": "Type in an occupation by name or SOC code to see nationwide occupational transitions".Then underneath "Enter State (Optional)" it could say "Type in a state to see state-level average wage data. If no state is entered, national wage data will be shown."

This visualization shows the occupations which Sales Managers move to when they change occupation. The size of the box represents the transition share, which is the proportion of Sales Managers who move into a job in each other occupation when they switch jobs. We only break out individual occupations with transition shares greater than 0.2%. In the "occupation" view, the colors of the boxes represent occupation groups. In the "salary" view, the colors of the boxes represent the hourly pay of the occupation (nationwide/in Arkansas)

In the starting text at the top of the page, perhaps we could edit slightly to say: "JobHopper is a tool to explore new data on mobility between occupations in the US. This data was calculated by academic researchers using around 16 million resumes of U.S. workers (which were obtained and parsed by Burning Glass Technologies), and using occupation transitions made over 2002-2016. Note that the sample is very large but may not always be fully representative of transitions for each occupation. We believe this tool can help program managers, policy analysts and job coaches explore occupational transitions that millions of job changers have made in recent years. Understanding these transitions can support labor market analysis, program and policy development, and individual job seekers’ aspiration" Or something like that? We can workshop the exact wording. (I know I already changed this blurb once - so feel free to table for now. More broadly: I want to think a little more about what kind of caveats we want to add to the main text and the "About" section about the representativeness of the data. I will think and be in touch, but also, it would be really helpful if maybe there is a way you could show us how we can directly edit this if it's not too difficult -- so that, when the tool is handed over, we can still have the option to edit this. So feel free to table this comment for now and we can work on it later if that's easier).

Skipped This because a version of it was done already:
When you enter an occupation and state, the table comes up with "Which occupations do OCCUPATION move to in STATE"? (e.g. which occupations do drivers move to in Arkansas?". This is misleading because the transitions are at the national level not the state level. Could you remove this and just keep it saying "Which occupations do OCCUPATION move to when they switch occupation?" (i.e no state mentioned)

At the bottom of the tree chart, there is an extra "s" for when it lists the occupation "e.g. This visualization shows the occupations which Sales Managerss move to"

### PR DESCRIPTION
**Pull request by jedpittman**
closes #366 
Jeff, sorry, I did this one on the main jobhopper instead of my forked repo.

### CODE REVIEW

File: frontend/src/ui/D3Visualizations/TreemapWrapper.tsx [hunk 1]
```diff
@@ -53,11 +53,15 @@ export default function TreemapWrapper({
         selectedCategory={selectedCategory}
       />
       <CaptionText>
-        The treemap above shows the occupations which {selectedOccupation.name}{' '}
-        move to when they change occupation based on the observations in our
-        dataset. The transition share is the percentage of these observed{' '}
-        {selectedOccupation.name} who have moved into each of the occupations
-        listed.
+        This visualization shows the occupations which Sales Managers move to
```
Comment (jkoren) [inline frontend/src/ui/D3Visualizations/TreemapWrapper.tsx]: "Sales Managers" is hardcoded on lines 56 & 58.  It should be `{selectedOccupation.name}{' '}`

**Review by jkoren — CHANGES_REQUESTED** [review]
I made one comment.  Need to replace Sales Managers that is hardcoded.

File: frontend/src/ui/D3Visualizations/TreemapWrapper.tsx (hunk 1 above)
Comment (jedpittman) [reply frontend/src/ui/D3Visualizations/TreemapWrapper.tsx]: all set.
